line-length = 100
indent-width = 4

[lint]
exclude = ["tests/**", "__pycache__/**"]
select = [
    "E",   # Pycodestyle errors
    "F",   # Pyflakes
    "W",   # Pywicked
    "B",   # Flake8-bugbear
    "C4",  # Flake8-comprehensions
    "I",   # Isort
    "N",   # PEP8-Naming
    "PGH", # Flake8-pygments
    "PTH", # Flake8-pytest-helper
    "RET", # Flake8-return
    "RUF", # Ruff-specific rules
    "SIM", # Flake8-simplify
    "UP",  # Flake8-pyupgrade
    "YTT", # Flake8-2020
]

ignore = [
    "RET501", # unnecessary-return-none (RET501)
]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Ensure that all files use the same line endings.
# This is important for cross-platform compatibility.
line-ending = "lf"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
